# Generated by Django 5.2.3 on 2026-05-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pick_count', models.IntegerField(default=10)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tests.test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.testpool'),
        ),
    ]
