# Generated by Django 5.2.3 on 2026-05-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testpool_question_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Savol uchun izoh yoki tushuntirish', null=True),
        ),
    ]
